using espacioEmpleado;

Cargos cargo1 = Cargos.Auxiliar, cargo2 = Cargos.Ingeniero, cargo3 = Cargos.Especialista;
DateTime fechaNac1 = new DateTime(2003, 4, 11);
DateTime fechaNac2 = new DateTime(2000, 2, 19);
DateTime fechaNac3 = new DateTime(1987, 10, 24);
DateTime fechaIng1 = new DateTime(2019, 6, 2);
DateTime fechaIng2 = new DateTime(2012, 2, 22);
DateTime fechaIng3 = new DateTime(2005, 1, 17);
Empleado empleado1 = new Empleado(cargo1, "José", "Ramirez", fechaNac1, 'C', 'M', fechaIng1, 76000);
Empleado empleado2 = new Empleado(cargo2, "Carla", "Ortiz", fechaNac2, 'S', 'F', fechaIng2, 69000);
Empleado empleado3 = new Empleado(cargo3, "Marcos", "Ibañez", fechaNac3, 'C', 'M', fechaIng3, 81000);
Console.WriteLine(fechaNac1);
empleado1.mostrarAntiguedad();
empleado1.mostrarEdad();
empleado1.mostrarTmpJubilacion();
empleado1.mostrarSueldo();
empleado2.mostrarSueldo();
empleado3.mostrarSueldo();
Console.WriteLine("Años para jubilarse del empleado: "+ empleado1.TmpAJubilarse);
empleado1.mostrarProxAJubilarse(empleado1, empleado2, empleado3);
empleado1.mostrarMontoTotalSueldos(empleado1, empleado2, empleado3);